In [1]:
import healpy as hp
import numpy as np
import pandas as pd

In [2]:
def hpix_disc(ra, dec, nside=16384, radius_arcmin=3.0, inclusive=True):
    """
    Return the HEALPix (NEST) pixel indices within radius_arcmin
    of (ra, dec), at the given nside.
    """
    theta = np.radians(90.0 - dec)
    phi = np.radians(ra)
    vec = hp.ang2vec(theta, phi)
    radius_rad = np.radians(radius_arcmin / 60.0)
    return hp.query_disc(nside, vec, radius_rad, nest=True, inclusive=inclusive)

In [3]:
pathdata = '/Users/jimenagonzalez/research/DSPL/Hybrid_SL_Modeling/data/candidates_data/'
filename_data = 'sledcand_old.csv'
data = pd.read_csv(pathdata + filename_data)

data.head()

,COADD_OBJECT_ID,EXP_SCORE,TILENAME,RA,DEC,FLUX_RADIUS_G,FLUX_RADIUS_R,FLUX_RADIUS_I,KRON_RADIUS,MAG_AUTO_G,MAG_AUTO_R,MAG_AUTO_I,MOF_BDF_G_1,MOF_BDF_G_2,MOF_BDF_T,EXT_COADD,MAG_APER_4_G,MAG_APER_4_R,MAG_APER_4_I
0,870438840,0.5,DES1959-5248,299.389196,-52.606592,7.369224,7.533865,7.339421,3.769610,20.364841,18.874065,18.343222,-0.070296,-0.122505,8.667003,3,22.535849,20.914185,20.302483
1,872552908,1.0,DES2001-5540,300.920093,-55.803160,8.979646,7.087684,6.522683,3.500000,21.153446,19.553114,18.748962,-0.209734,-0.083165,18.835751,3,23.028400,21.011065,20.068295
2,881198330,0.0,DES2050-5748,312.188244,-57.791482,7.224463,5.898704,5.684735,3.500000,20.578129,19.279715,18.744473,0.052258,0.320367,5.677221,3,22.328573,20.587727,19.991379
3,888195894,0.0,DES2037-5248,308.773877,-52.951090,7.221684,6.962849,6.864975,3.577494,21.139896,19.559956,18.842449,0.036601,0.071875,5.395121,3,22.983912,21.276869,20.485367
4,889856193,0.0,DES2038-4706,309.544708,-46.831819,6.642945,6.542537,6.308135,3.500000,21.146551,19.497349,18.624556,0.111662,0.229087,6.079993,3,22.856127,21.104959,20.108000

In [4]:
all_pix = set()
for ra, dec in zip(data['RA'], data['DEC']):
    all_pix.update(hpix_disc(ra, dec, nside=16384, radius_arcmin=5.0))

hpix_table = pd.DataFrame({'hpix_4096': sorted(all_pix)})
hpix_table.to_csv('stars_data/hpixstars_sledcand.csv', index=False)

In [5]:
hpix_table.head()

   hpix_4096
0     534526
1     534527
2     535839
3     535859
4     535860